### ISSUE TITLE
Evaluating ShiftResNet on CIFAR-10 returns AttributeError

### ISSUE THREAD

**Issue by briancylui** [alvinwan/shiftresnet-cifar#8]
Running `python eval.py --model=checkpoint/shiftresnet20_3.0.t7` in root directory returns
```
Files already downloaded and verified
==> Resuming from checkpoint..
Reading from model checkpoint/shiftresnet20_3.0.t7
...(some SourceChangeWarnings)...
Traceback (most recent call last):
  File "eval.py", line 90, in <module>
    checkpoint = torch.load(model)
  File "/cvgl2/u/brianlui/shiftresnet/shift/local/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/cvgl2/u/brianlui/shiftresnet/shift/local/lib/python2.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
AttributeError: 'module' object has no attribute 'ShiftConv'
```

Why does the ShiftNet `shiftresnet20_3.0.t7` model pretrained on CIFAR-10 give a `module` object that has no attribute `ShiftConv`?  I was able to fix other bugs using StackOverflow, but this one seems to be model-specific.  Would appreciate any advice - thank you!

**Comment by briancylui** [comment]
As a follow-up, the details of the machine running the above code are:
```
OS: Linux
Python: 2.7
Pytorch: 0.4.1
CUDA: 9.0
```

**Comment by Yang-YiFan** [comment]
One possible solution is switching to Pytorch 0.4.0, I faced a similar issue when loading models trained under 0.4.0 to 0.4.1. Not sure if the solution is applicable to your case.

**Comment by briancylui** [comment]
Thank you @Yang-YiFan!  I just now switched to Pytorch 0.4.0 and the corresponding torchvision, but the same error unfortunately persists.  Any advice?

**Comment by meteorshowers** [comment]
@briancylui  does it faster than normal conv?
How about the speed.

**Comment by jlhou** [comment]
Hello  guys, I have exactly the same problem as you.How did you solve it

**Comment by XingJun940207** [comment]
I got the same error on pytorch 0.4.0 and 0.4.1, have you solved it now?
